{
 "title": "Data Governance Hub Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Data Governance Hub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Quality",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hivemq_data_governance_hub_data_validation_custom_counters_good_machine_messages / (com_hivemq_data_governance_hub_data_validation_custom_counters_good_machine_messages + com_hivemq_data_governance_hub_data_validation_custom_counters_bad_machine_messages)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Good Data / Bad Data",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_hivemq_data_governance_hub_data_validation_custom_counters_good_machine_messages[1m])",
     "legendFormat": "Good Data"
    },
    {
     "expr": "increase(com_hivemq_data_governance_hub_data_validation_custom_counters_bad_machine_messages[1m])",
     "legendFormat": "Bad Data"
    }
   ]
  },
  {
   "title": "Actice Policies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hivemq_policy_persistence_size_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Policies Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "com_hivemq_policy_persistence_size_bytes",
     "legendFormat": "Policy memory footprint"
    }
   ]
  },
  {
   "title": "Policy Executions per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_hivemq_data_governance_hub_data_validation_policies_successful_count[1m]) + increase(com_hivemq_data_governance_hub_data_validation_policies_failed_count[1m])",
     "legendFormat": "Policy Executions per minute"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Schemas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hivemq_schema_persistence_size_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Schemas Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "com_hivemq_schema_persistence_size_bytes",
     "legendFormat": "Schema memory footprint"
    }
   ]
  },
  {
   "title": "Schema Validations per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_hivemq_data_governance_hub_data_validation_schema_validations_successful_count[1m]) + increase(com_hivemq_data_governance_hub_data_validation_schema_validations_failed_count[1m])",
     "legendFormat": "Schema Validations "
    }
   ]
  },
  { "title": "HiveMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Incoming Publishes per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "increase(com_hivemq_messages_incoming_publish_rate_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Publishes per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "increase(com_hivemq_messages_outgoing_publish_rate_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}