apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
  - name: Postgres
    type: postgres
    url: postgres:5432
    user: admin
    secureJsonData:
      password: 'postgres'
    jsonData:
      database: hivemq
      sslmode: 'disable'
