services:
  hivemq:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:8889:8889"
    volumes:
      - ../config/hivemq-config.xml:/opt/hivemq/conf/config.xml
      - ../config/hivemq.lic:/opt/hivemq/license/hivemq.lic
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8889/api/v1/health/readiness" ]
      interval: 5s
      retries: 10
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ../config/grafana-datasource.yml:/etc/grafana/provisioning/datasources/all.yaml
volumes:
  prom_data: